name: Build Python App

on:
  push:
    branches: ["master"]
    paths-ignore: ["dist/**"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build using PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile --name proteus --add-data "static:static" app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proteus
          path: dist/proteus

      - name: Commit built binary
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Add updated built binary"
          add: "dist/proteus"
