name: Build Python App

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.6.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build using PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller app.py --onefile --name proteus --add-data "static:static" app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proteus
          path: dist/proteus
